### ISSUE TITLE
Can't import in Jest

### ISSUE THREAD

**Issue by iSarCasm** [fnando/i18n#26]
## Description

The I18n works but not in my Jest tests where it fails with the following error:
```
Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/igortsykalo/workspace/covalent-ojt/node_modules/i18n-js/dist/import/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export { I18n } from "./I18n";
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import { I18n } from 'i18n-js';
        | ^
      2 | import en from './locales/en.json';
      3 | import es from './locales/es.json';
      4 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (app/javascript/i18n.js:1:1)
```
I've tried to follow Jest recommendations and added following to my `jest.config.js`:
```
  transform: {
    '^.+\\.(js|jsx)$': 'babel-jest',
  },
transformIgnorePatterns: ['<rootDir>/node_modules/(?!(i18n-js)/)'],
  ```
  But this still did not help. I am using many other node_modules (react, material-ui, axios, etc.), but this is the first one that caused me issues. 

## How to reproduce

Use `i18n-js` with jest

## What do you expect

works

## What happened instead

fails

## Software:

- Gem version: v4
- Ruby version: 2.7

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by iSarCasm** [comment]
Turns out Jest was not picking up on our `.babelrc` file, so the fix was to use `babel.config.js` instead.

**Comment by fnando** [comment]
Can you please share the jest config you had to add to make it work?

**Comment by iSarCasm** [comment]
@fnando for some reason `i18n-js` requires babel transformation with `@babel/preset-env` if used via `node_modules/i18n-js/dist/import/I18n.js`. I was able to skip babel when imported from here `node_modules/i18n-js/dist/require/I18n.js` like this `const { I18n } = require('i18n-js/dist/require/index');`

**Comment by lucasrocali** [comment]
`jest.mock('i18n-js', () => {
  return jest.requireActual('i18n-js/dist/require/index');
});`

**Comment by lucasrocali** [comment]
````
jest.mock('i18n-js', () => {
  return jest.requireActual('i18n-js/dist/require/index');
});
````
