### ISSUE TITLE
Bug:  Package not working with Next.js

### ISSUE THREAD

**Issue by Michal9402** [fnando/i18n#55]
## Description

Package seems to not work with Next.js anymore. 

## How to reproduce

`npx create-next-app i18n-test --ts`
`npm i i18n-js@latest`

Create `data.json` in root folder.
```
{
    "Hello" : "Guten morgen"
}
```

Create i18n.ts in root folder.

```
import { I18n } from "i18n-js";
import data from './data.json'

export const i18n = new I18n({
    ...data
})
```

Use translation in any page to reproduce the bug.

## Software:

node: 16.13.2
next: 13.2.3
react: 18.2.0

## Full backtrace

```
error - /Users/michal/Documents/projects/i18n-test/node_modules/i18n-js/dist/import/index.js:1
export { I18n } from "./I18n";
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.i18n-js (/Users/michal/Documents/projects/i18n-test/.next/server/pages/index.js:54:18)
    at __webpack_require__ (/Users/michal/Documents/projects/i18n-test/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./i18n.ts:5:65)
    at Object../i18n.ts (/Users/michal/Documents/projects/i18n-test/.next/server/pages/index.js:32:1)
    at __webpack_require__ (/Users/michal/Documents/projects/i18n-test/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.tsx:9:63)
    at Object../pages/index.tsx (/Users/michal/Documents/projects/i18n-test/.next/server/pages/index.js:43:1)
    at __webpack_require__ (/Users/michal/Documents/projects/i18n-test/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/michal/Documents/projects/i18n-test/.next/server/pages/index.js:97:39)
    at /Users/michal/Documents/projects/i18n-test/.next/server/pages/index.js:98:28
    at Object.<anonymous> (/Users/michal/Documents/projects/i18n-test/.next/server/pages/index.js:101:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.requirePage (/Users/michal/Documents/projects/i18n-test/node_modules/next/dist/server/require.js:88:12)
    at /Users/michal/Documents/projects/i18n-test/node_modules/next/dist/server/load-components.js:49:73
    at async Object.loadComponentsImpl [as loadComponents] (/Users/michal/Documents/projects/i18n-test/node_modules/next/dist/server/load-components.js:49:26)
    at async DevServer.findPageComponentsImpl (/Users/michal/Documents/projects/i18n-test/node_modules/next/dist/server/next-server.js:599:36) {
  page: '/'
}

```

**Comment by tamangupta1999** [comment]
I am also facing the same issue. any one has any solution for the above problem.

**Comment by tamangupta1999** [comment]
Please use version @3.9.2 not throwing error

**Comment by fnando** [comment]
I believe this is an error on your build pipeline. Things like esbuild and webpack will translate `export` into something browsers can really use. I never used Next.js, but a search brought this up: https://github.com/vercel/next.js/issues/31518
